### ISSUE TITLE
Plugin fails to load on Spigot 1.8.7

### ISSUE THREAD

**Issue by bjmc** [wensheng/JuicyRaspberryPie#1]
I'm getting this error when starting Spigot with the JuicyRaspberryPie plugin. This is on Ubuntu 15.04 using Java 7 (openjdk-7-jre). Please let me know if any other details would help for debugging.

`[23:44:40 ERROR]: Could not load 'plugins/JuicyRaspberryPie.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/wensheng/plugins/JuicyRaspberryPie : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.7.jar:git-Spigot-44c59bf-1880a9c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.7.jar:git-Spigot-44c59bf-1880a9c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.7.jar:git-Spigot-44c59bf-1880a9c]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.7.jar:git-Spigot-44c59bf-1880a9c]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.7.jar:git-Spigot-44c59bf-1880a9c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot-1.8.7.jar:git-Spigot-44c59bf-1880a9c]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.UnsupportedClassVersionError: org/wensheng/plugins/JuicyRaspberryPie : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_79]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_79]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_79]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_79]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_79]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_79]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.7.jar:git-Spigot-44c59bf-1880a9c]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.7.jar:git-Spigot-44c59bf-1880a9c]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
	at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.7.jar:git-Spigot-44c59bf-1880a9c]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.7.jar:git-Spigot-44c59bf-1880a9c]
	... 6 more`

**Comment by aisoy** [comment]
Same error on Ubuntu 14.04. Tested with both java sdk 6 and 7. Any idia?

**Comment by wensheng** [comment]
Please use JDK 8( or jre 8) from oracle. I tried just now and it works on both windows and Ubuntu 14.04, with spigot 1.8.8.

The plugin use a java8 feature (thought in retrospect, it's not necessary) so it only works with Java 8
